-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "onboardingDraft" JSONB,
ADD COLUMN     "onboardingStep" INTEGER NOT NULL DEFAULT 1,
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "shortName" DROP NOT NULL,
ALTER COLUMN "taxNumber" DROP NOT NULL,
ALTER COLUMN "contactName" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "district" DROP NOT NULL,
ALTER COLUMN "sector" DROP NOT NULL;
